### PR TITLE
Rename "video" -> "section"

### PR DESCRIPTION
**Pull request by juandes**
Not sure if the term "video" is intended, or just a small oops overlooked during the transition of the course.

### CODE REVIEW

**Comment by floscha** [comment]
The term "video" in fact also appears in [a couple of other places](https://github.com/ines/spacy-course/search?q=video) during the course. Also, I figured that "lesson" might be the most suitable replacement term, but that's just my personal preference 😉

**Comment by juandes** [comment]
@floscha the term "lesson" suits better :). I'll replace the others too.

**Comment by ines** [comment]
Ahhh, perfect – thanks so much! 🙏

**Comment by juandes** [comment]
Coolio, you're welcome :)

**Pull request merged**
