### PR TITLE
Portuguese translation to V3

### PR DESCRIPTION
**Pull request by Cristianasp**
Portuguese adaptation of course from spacy 2 to spacy 3. 
Used the changes made in the english version of the course as a baseline of comparison, from PR #104

### CODE REVIEW

**Comment by Cristianasp** [comment]
I have also adapted all exercises that were using the english pipeline to use the portuguese pipeline.
I have tested all exercises and they are working fine.
Except for:
exercise 02.13: it seams that the tokenizer is not working properly
exercise 03.1: pipeline did not extract PERSON and GPE

**Comment by Cristianasp** [comment]
@ines , as soon as you have updated the course in the platform, I will do a final review :)

**Comment by ines** [comment]
@Cristianasp Thanks 🙏 I've updated the PR and tests but it seems like there are still a couple of test failures related to the exercises where the expected output doesn't match the test: https://dev.azure.com/explosion-ai/Public/_build/results?buildId=16026&view=logs&j=f1d52934-b974-5ece-337e-e658a4411382&t=25745add-d8f1-5bdf-c7de-2e51e93603d8&l=1164

Could you take a look at them? Maybe the tests just need to be updated here or we need to pick different examples 🙂

**Comment by Cristianasp** [comment]
Here it goes ! All portuguese exercises reviewed and tested :-) It seams that everything is ok now. 🙏

**Comment by ines** [comment]
Awesome, thank you! 🙏 Will go ahead and merge this now and update the Binder image and then you can test it one more time once it's live. And if it all looks good, we'll go ahead and promote it to the community 😊

**Pull request merged**
